version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - ./redis/data:/data
      - ./redis:/usr/local/etc/redis
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: unless-stopped